#!/usr/bin/env bash
./scb.creator.sh -b resources -f 7850 -t 7900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7900 -t 7950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7950 -t 8000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8000 -t 8050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8050 -t 8100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8100 -t 8150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8150 -t 8200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8200 -t 8250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8250 -t 8300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8300 -t 8350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8350 -t 8400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8400 -t 8450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8450 -t 8500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8500 -t 8550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8550 -t 8600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8600 -t 8650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8650 -t 8700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8700 -t 8750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8750 -t 8800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8800 -t 8850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8850 -t 8900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8900 -t 8950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8950 -t 9000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9000 -t 9050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9050 -t 9100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9100 -t 9150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9150 -t 9200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9200 -t 9250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9250 -t 9300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9300 -t 9350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9350 -t 9400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9400 -t 9450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9450 -t 9500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9500 -t 9550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9550 -t 9600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9600 -t 9650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9650 -t 9700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9700 -t 9750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9750 -t 9800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9800 -t 9850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9850 -t 9900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9900 -t 9950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9950 -t 10000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10000 -t 10050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10050 -t 10100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10100 -t 10150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10150 -t 10200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10200 -t 10250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10250 -t 10300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10300 -t 10350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
