#!/usr/bin/env bash
./scb.creator.sh -b resources -f 5400 -t 5450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5450 -t 5500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5500 -t 5550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5550 -t 5600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5600 -t 5650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5650 -t 5700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5700 -t 5750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5750 -t 5800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5800 -t 5850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5850 -t 5900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5900 -t 5950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 5950 -t 6000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6000 -t 6050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6050 -t 6100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6100 -t 6150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6150 -t 6200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6200 -t 6250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6250 -t 6300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6300 -t 6350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6350 -t 6400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6400 -t 6450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6450 -t 6500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6500 -t 6550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6550 -t 6600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6600 -t 6650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6650 -t 6700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6700 -t 6750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6750 -t 6800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6800 -t 6850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6850 -t 6900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6900 -t 6950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 6950 -t 7000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7000 -t 7050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7050 -t 7100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7100 -t 7150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7150 -t 7200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7200 -t 7250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7250 -t 7300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7300 -t 7350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7350 -t 7400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7400 -t 7450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7450 -t 7500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7500 -t 7550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7550 -t 7600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7600 -t 7650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7650 -t 7700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7700 -t 7750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7750 -t 7800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7800 -t 7850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7850 -t 7900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7900 -t 7950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 7950 -t 8000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8000 -t 8050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8050 -t 8100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8100 -t 8150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8150 -t 8200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8200 -t 8250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8250 -t 8300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8300 -t 8350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8350 -t 8400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8400 -t 8450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8450 -t 8500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8500 -t 8550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8550 -t 8600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8600 -t 8650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8650 -t 8700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8700 -t 8750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8750 -t 8800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8800 -t 8850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8850 -t 8900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8900 -t 8950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 8950 -t 9000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9000 -t 9050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9050 -t 9100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9100 -t 9150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9150 -t 9200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9200 -t 9250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9250 -t 9300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9300 -t 9350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9350 -t 9400 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9400 -t 9450 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9450 -t 9500 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9500 -t 9550 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9550 -t 9600 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9600 -t 9650 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9650 -t 9700 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9700 -t 9750 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9750 -t 9800 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9800 -t 9850 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9850 -t 9900 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9900 -t 9950 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 9950 -t 10000 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10000 -t 10050 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10050 -t 10100 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10100 -t 10150 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10150 -t 10200 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10200 -t 10250 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10250 -t 10300 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
./scb.creator.sh -b resources -f 10300 -t 10350 -c /home/christopher/IdeaProjects/systematik-catalogue-builder/scb.creator/build/distributions/scb.creator-0.2.0-SNAPSHOT/bin/scbconfig-test-remote.yml
