PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sc: <http://iiif.io/api/presentation/2#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX exif: <http://www.w3.org/2003/12/exif/ns#>
PREFIX svcs: <http://rdfs.org/sioc/services#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
CONSTRUCT {?canvas sc:metadataLabels ?llist .
?canvas rdf:type sc:Canvas .
?canvas rdfs:label ?clabel .
?canvas exif:width ?width .
?canvas exif:height ?height .
?lmid rdf:first ?label .
?label rdfs:label ?k .
?label rdf:value ?v .
?lmid rdf:rest ?llast .
?canvas sc:hasImageAnnotations ?anno .
?anno oa:hasBody ?image .
?image svcs:has_service ?service .
?image exif:width ?iwidth .
?image exif:height ?iheight .
?service rdf:type ?servicetype .
?service doap:implements ?serviceprofile .
}
WHERE {
values ?mvalue {"1672"} .
?canvas sc:metadataLabels ?llist .
?canvas rdfs:label ?clabel .
?canvas exif:width ?width .
?canvas exif:height ?height .
?llist rdf:rest* ?lmid .
?lmid rdf:first ?label .
?label rdfs:label ?k .
?label rdf:value ?mvalue .
?lmid rdf:rest ?llast .
?anno oa:hasTarget ?canvas.
?anno oa:hasBody ?image .
?image svcs:has_service ?service .
?image exif:width ?iwidth .
?image exif:height ?iheight .
?service rdf:type ?servicetype .
?service doap:implements ?serviceprofile .
}